# 带[ ]括号的，就是多选，不带的就是单选,所有选项的 开对应true，关对应false，自行根据需要调整
boss:
  sayHi: [
    "您好,我有7年工作经验,还有AIGC大模型、Java,Python,Golang和运维的相关经验,希望应聘这个岗位,期待可以与您进一步沟通,谢谢！"
  ] #必须要关闭boss的自动打招呼
  keywords: [ "Java", "Golang" ] # 需要搜索的职位,会依次投递
  industry: [ "不限" ] # 公司行业，只能选三个，相关代码枚举的部分，如果需要其他的需要自己找
  cityCode: [ "全国" ] # 只列举了部分,如果没有的需要自己找：目前支持的：全国 北京 上海 广州 深圳 成都
  experience: [ "在校生" ] # 工作经验："应届毕业生", "1年以下", "1-3年", "3-5年", "5-10年", "10年以上"
  jobType: "不限" #求职类型："全职", "兼职"
  salary: "不限" # 薪资（单选）："3K以下", "3-5K", "5-10K", "10-20K", "20-50K", "50K以上"
  degree: [ "本科" ] # 学历: "初中及以下", "中专/中技", "高中", "大专", "本科", "硕士", "博士"
  scale: [ "20-99人", "100-499人" ] # 公司规模："0-20人", "20-99人", "100-499人", "500-999人", "1000-9999人", "10000人以上"
  stage: [ "不限" ] # "未融资", "天使轮", "A轮", "B轮", "C轮", "D轮及以上", "已上市", "不需要融资"
  expectedSalary: [ 20 ] #期望薪资，单位为K，第一个数字为最低薪资，第二个数字为最高薪资，只填一个数字默认为最低薪水
  filterDeadHR: true # 是否过滤不活跃HR,该选项会过滤半年前活跃的HR
  enableAI: true #开启AI检测与自动生成打招呼语
  fakeUserAction: false #开启虚假用户行为, 会导致投简历速度大大降低(跟真人投递速度相仿), 但对Boss账户的封禁可能变小

job51:
  jobArea: [ "上海" ]  #工作地区：目前只有【北京 成都 上海 广州 深圳】
  keywords: [ "java", "python", "go", "golang", "大模型", "软件工程师" ] #关键词：依次投递
  salary: [ "不限" ] #薪资范围：只能选5个【"2千以下", "2-3千", "3-4.5千", "4.5-6千", "6-8千", "0.8-1万", "1-1.5万", "1.5-2万", "2-3万", "3-4万", "4-5万", "5万以上"】

lagou:
  keywords: [ "AI工程师","Java","Golang","Python" ] #搜索关键词
  cityCode: "上海" #拉勾城市名没有限制,直接填写即可
  salary: "不限" #薪资【"不限","2k以下", "2k-5k", "5k-10k", "10k-15k", "15k-25k", "25k-50k", "50k以上"】
  scale: [ "不限" ] #公司规模【"不限","少于15人", "15-50人", "50-150人", "150-500人", "500-2000人", "2000人以上"】
  gj: "在校/应届,3年及以下"

liepin:
  cityCode: "天津" # 目前支持的：全国 北京 上海 广州 深圳 成都
  keywords: [ "Java" ]
  #salary: "15$30" # 填 15$30 代表 15k-30k
  # 排除的公司名
  excludeCompany: "联合永道,亿达信息,政通科技,浙江,联想,讯锡,诚迈科技,中软国际,中科创达,博彦科技,软通动力,文思海辉,东软,科瑞,高伟达,中智,外服,中企人力,易才,蚂蚁HR,紫川软件,易思博,麦亚信,长亮,京北方,微创,鼎驰,拓保软件,武汉佰钧成,博悦科创,亿科达,青柏信息,博雅互动,博奥特科技,金证股份,印孚瑟斯,前海泰坦科技,福瑞兰斯,法本信息,柯莱特,中科软,浪潮,亚信科技,新致软件,IBM外包,北京外企德科,德科信息,海隆软件,宇信科技,汉德,科蓝,亿迪,海博拓天,神马,博朗,中和软件,亿达,凯捷,埃森哲,普华永道信息技术,信必优,润和,神州数码,华信,法本,天阳科技,慧博,赛意信息,山东中创,百得思维,屹通软件,深圳信科科技,凌志软件,数字动力,软通,行至简,中金电信,京北方,京东,蚂蚁,快手,美团,字节,BOSS,360,上海,贝壳,滴滴,顺丰,阿里,小米,中科,众安,上海,浙江,深圳,南京,外包,外派,政府,银行,Python,python,Andorid,andorid,C,.NET,.net,安卓,对日,政企"
  # 包含的工作名
  containsJobName: "Java,java,JAVA"
  # 排除的公司名
  excludeJobName: "外包,外派,政府,银行,Python,python,Andorid,andorid,C,.NET,.net,安卓,对日,政企"

zhilian:
  cityCode: "上海"
  salary: "25001,35000" #薪资区间
  keywords: [ "AI工程师", "AIGC", "Java", "Python", "Golang" ]
