common:
  sayHi: "您好，我有7年工作经验，还有AIGC大模型、Java，Python，Golang和运维的相关经验，希望应聘这个岗位，期待可以与您进一步沟通，谢谢！"

boss:
  keywords: ["大模型工程师", "AIGC", "AI", "Java", "Python", "Golang"]

51job:
  keywords: ["java", "python", "go", "golang", "大模型", "软件工程师"]

lagou:
  keyword: "Java"

liepin:
  isSayHi: false
  cityCode: "010"
  keywords: ["Java", "Python", "Golang", "大模型"]

zhilian:
  cityCode: "530"
  salaryScope: "25001,35000"
  keywords: ["Java", "AIGC", "大模型", "Python", "Golang"]